FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
RUN npm audit fix
RUN npm install -g @angular/cli
RUN npm i -D puppeteer karma-chrome-launcher

COPY . .

CMD ["ng", "serve", "--host", "0.0.0.0"]



